version: '3'

services:
  master:
    image: marcel1199/rtl_433-mqtt_rfraw_support:debian-master
    build:
      context: ../..
      args:
        - debianVersion=latest
        - rtl433GitRevision=mqtt_rfraw_support
